language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'io.js'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lanetix-script' ]; then cd .. && eval "mv $currentfolder generator-lanetix-script" && cd generator-lanetix-script; fi
